---
- name: Install Smar-Home App
  hosts: all

  vars:
    dest: /tmp/gusev/

  tasks:
    - name: Install JDK for CentOS
      yum:
        name: java-11-openjdk-devel
        state: latest
      when:
        ansible_distribution == "CentOS"
      become: yes
      become_method: sudo

    - name: Install JDK for Debian
      apt:
        name: openjdk-11-jdk
        state: latest
      when:
        ansible_distribution == "Debian"
      become: yes
      become_method: sudo

    - name: Check if directory exists
      stat:
        path: "{{ dest }}"
      register: folder

    - name: Make temporary directory
      shell: "mkdir {{ dest }}"
      when: folder.stat.exists == false

    - name: Copy JAR
      copy:
        src: ../target/smart-home-1.0-SNAPSHOT-jar-with-dependencies.jar
        dest: "{{ dest }}/smart-home.jar"

    - name: Copy config
      copy:
        src: ../smart-home-1.js
        dest: "{{ dest }}/smart-home-1.js"

    - name: Execute JARR
      ansible.builtin.shell:
        cmd: java -jar {{ dest }}/smart-home.jar
...